package handlers

import (
	"database/sql"
	"log"

	"github.com/algo-matchfund/grants-backend/gen/restapi/operations"
	"github.com/algo-matchfund/grants-backend/internal/database"
	"github.com/go-openapi/runtime/middleware"
)

type getProjectMatchCalculationHandler handler

func (h *getProjectMatchCalculationHandler) Handle(params operations.GetProjectMatchCalculationParams) middleware.Responder {
	log.Printf("GET /projects/%s/calculate", params.ID)

	newMatch, err := h.db.GetProjectMatchCalculation(params.ID, params.Amount)

	if err != nil {
		if err == sql.ErrNoRows {
			return operations.NewGetProjectMatchCalculationNotFound()
		}

		log.Println(err)
		return operations.NewGetProjectMatchCalculationInternalServerError()
	}

	return operations.NewGetProjectMatchCalculationOK().WithPayload(newMatch)
}

// NewGetProjectMatchCalculationHandler creates a handler for getting match generated by user
func NewGetProjectMatchCalculationHandler(db *database.GrantsDatabase) operations.GetProjectMatchCalculationHandler {
	return &getProjectMatchCalculationHandler{db}
}
