CREATE USER grants WITH PASSWORD 'secret';
ALTER USER grants WITH SUPERUSER;
CREATE DATABASE grants;
GRANT ALL PRIVILEGES ON DATABASE grants TO grants;

CREATE USER keycloak WITH PASSWORD 'secret';
CREATE DATABASE keycloak;
GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;
