FROM alpine:latest

# Install updates and required packages
RUN apk update \
&&  apk upgrade \
&&  apk add \
        docker-cli \
        git \
        make \
        cmake \
        bash \
        python3
