get:
  summary: "Get information about your own project"
  responses:
    200:
      description: "successful operation"
      schema:
        $ref: "../schemas/Project.yaml"
    403:
      $ref: "../responses/Forbidden.yaml"
    404:
      $ref: "../responses/NotFound.yaml"
    500:
      $ref: "../responses/InternalError.yaml"